spring.application.name=Library-Application-CRUD

#H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:librarydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#Jap Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

#H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Server Configuration
server.port=4041

#Logging Configuration
logging.level.org.springframework=INFO
logging.level.com.example.library=DEBUG

#Actuator Endpoints
management.endpoints.web.exposure.include=*
